language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install .
script:
- python -m unittest
deploy:
  provider: pypi
  user: johnliu55tw
  password:
    secure: F7iarnXjw3bKBeFdg2gdxavVpTJ2SjoqodygkGbZZ5d48u1H9x7xVczSb6Cu1Nukre4eb3iEAJMRcY6zJFdptoH5RfcWjnAE8ix2hdM4VJBOQ7hSK7ZMmwu6oW4S0W3f57PvofwJM1bGd2Pa+BHRSPLnmrGCV/6O0ZV8lPM+hVHMb1JYukmh1ustCLBaFj+Z4uRMrfD6CuP9Y8YLagJElhGZT3m0acjvTCJCWRnwC+Z9zQ6KL1aRsQOFfebHiEYUPx6TgE3E6AapocCrlmZzXwZdQq2B/Z2Qa2gCx5u2Fbe57vJfSUKfZ/JUUUMVUw0ZCe4GwS1h5r6IUwd0YQjbLAi+DDxIZkymmH7CGaKekui5Mq2cGIOW0sHomelbGEC7AHlyfUVIGpCsD8PIxtjeUSqbkNSxpKoPwNskd+NtYsVfdEbvJKhc9tQpJAnhR+uHV5ZXMaPP2q6Nu/xXaKu6j0auJ9SnIolSgueYYktzGYFGv8urxpHgYPpiAWODZ+ge6YAOTTm0C6+hZIogbTOB6A9zuGL8NukJ3m5T1A9c44tftz+rFkx4caGwSMyXXNe03hFhrDn07zAfHqp/d4EWlfl4YF9vMBkxBDIRENL+zi3CLErYFVYq1DkD8fRndtR4RJq52qkV7bG5sTqNgSQI1b1necq+jGzhnV9NWed8Yuc=
  on:
    tags: true
